name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: akshay-sharma062
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push Snake SVG to the output branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}   # ✅ Correct token usage
          branch: output                     # ✅ or master/main as needed
          directory: dist                    # where your snake SVG is saved
