name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Generate the snake files into dist/
      - uses: Platane/snk@master
        with:
          github_user_name: akshay-sharma062
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to output branch (for GitHub Pages)
      - name: Push Snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # where to push the dist folder
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Use your Personal Access Token stored as 'PAT'
